[package]
name = "bfrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "*"
bfrs_input = { path = "../../lib/bfrs_input" }

[dependencies.bfrs_common]
path = "../../lib/bfrs_common"
